services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    entrypoint: ["bash"]
    command: ["scripts/post_create.sh"]
    volumes:
      - .:/app
    working_dir: /app
